# Generated by Django 3.1.3 on 2021-02-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210127_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
