# Generated by Django 3.1.3 on 2021-05-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
